---
- name: Set up local for Chameleon
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
    - include_tasks: ./tasks/add_vm_to_hosts.yaml
      vars:
        ips: "{{core_network_ips}}"
        group_name: core_network
    - include_tasks: ./tasks/install_ansible_requirements.yaml
      tags: install

- name: Free5gc Playbook
  hosts: core_network
  vars_files:
    - ./variables.yaml
  tasks:
    - name: Update and upgrade apt
      apt:
        update_cache: true
        upgrade: full
      become: true
      tags: install

    - name: Install underlying packages needed for free5gc
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      loop: "{{core_packages}}"
      become: true
      tags: install

    - include_tasks: ./tasks/install_mongodb.yaml

    - name: Start Mongodb
      ansible.builtin.systemd:
        state: started
        name: mongod

    - include_tasks: ./tasks/install_go.yaml
      tags: install

    # NOTE: this method is no longer functional in new version
    - include_tasks: ./tasks/install_node.yaml
      tags: install

    # NOTE: new free5gc version requires extra
    - include_tasks: ./tasks/set_up_networking.yaml

    # NOTE: just clones directories due to Make issues, post ansible script required, see below
    - include_tasks: ./tasks/build_core.yaml
    - name: Copy Make script to VM
      ansible.builtin.copy:
        src: ./scripts/make_free5gc.sh
        dest: "/home/{{home_dir}}/make_free5gc.sh"
        mode: '0777'

    - name: Copy test all script to VM
      ansible.builtin.copy:
        src: ./scripts/test_all_free5gc.sh
        dest: "/home/{{home_dir}}/free5gc/test_all_free5gc.sh"
        mode: '0777'

    - name: Copy networking script to VM
      ansible.builtin.copy:
        src: ./scripts/set_up_networking.sh
        dest: "/home/{{home_dir}}/set_up_networking.sh"
        mode: '0777'

    - include_tasks: ./tasks/set_free5gc_params.yaml
      vars:
        - core_ip: "{{core_network_internal_ip}}"

    # BUG: can execute the same command manually, and it works perfectly.
    # this is likely due to some sort of executable path inside the makefile not compatible with ansible
    # since ansible requires a full path
    # - name: Execute script that builds free5gc and gtp5g
    #  ansible.builtin.script: ./scripts/make_script.sh
    # - name: Execute script that tests free5gc
    #   ansible.builtin.script: ./scripts/test_free5gc.sh
...
