- name: "UFW for k8s APIserver"
  community.general.ufw:
    rule: limit
    state: enabled
    proto: tcp
    port: 6443
    comment: K8S API
  become: true

  # This will set ufw rules
- name: "UFW for etcd"
  community.general.ufw:
    rule: limit
    state: enabled
    proto: tcp
    port: 2379:2380
    comment: k8s etcd communication
  become: true
