# https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/
# wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
- name: Import the mongodb public key used in the package management system
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc
    state: present
  become: true

# echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
# sudo apt-get update
# sudo apt-get install -y mongodb-org
