# FIXME: this does not actually work yet
# source: https://waylonwalker.com/til/install-rust/
- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: Download rustup
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y

# FIXME: I don't know if this actually works...
- name: source bashrc
  shell: ". /home/{{home_dir}}/.bashrc"
