# sysctl -w net.ipv4.ip_forward=1
- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
  become: true

# shell: iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
- name: Modify iptables
  ansible.builtin.iptables:
    table: nat
    action: "append"
    chain: "POSTROUTING"
    out_interface: "{{network_interface}}"
    jump: "MASQUERADE"
    tcp_flags:
  become: true

# NEW REQUIREMENT: sudo iptables -A FORWARD -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1400

# shell: sudo systemctl stop ufw;
- name: Stop ufw
  ansible.builtin.systemd:
    state: stopped
    name: ufw
  become: true
